config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "lists#index"
  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end
    resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [ :new, :create ]

def new
  @bookmark = Bookmark.new
end

def create
  @bookmark = Bookmark.new(bookmark_params)
  @bookmark.list = @list
  if @bookmark.save
    redirect_to list_path(@list)
  else
    render template: "lists/show"
  end
end

def destroy
  @bookmark = Bookmark.find(params[:id])
  @bookmark.destroy
  redirect_to root_path
end

private

def find_list
  @list = List.find(params[:list_id])
end

def bookmark_params
  params.require(:bookmark).permit(:comment, :movie_id)
end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
    redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :imageUrl)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/new.html.erb
<h2>New bookmark</h2>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="home-banner">
  <h1><span id="banner-typed-text"></span></h1>
    <h1 class="banner-arrow">⌵</h1>
</div>

<p><span data-controller="typed-js"></span></p>

<div class="container">
  <div class="row cards">
    <% @lists.each do |list| %>
      <div class="col-4-sm">
          <h3><%= link_to list.name, list_path(list)%></h3>
        </div>
        <% end %>
    </div>
</div>

app/views/lists/new.html.erb
<div class="list-banner">
  <h1>Create your list</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name, placeholder: 'Add a list name' %>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<%# fix lines below %>
<% @list.bookmarks.each do |bookmark| %>
  <li class="list-group-item"><%= bookmark.comment %> <%= "Title: #{bookmark.movie.title}" %> <%= "Rating: #{bookmark.movie.rating}" %> </li>
<% end %>

<%= link_to "Add a bookmark", new_list_bookmark_path(@list) %>
<%= link_to "Back to lists", lists_path %>